language: java
install: true
sudo: false  # faster builds

# Cache gradle files:
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - openjdk8


before_script: 
  - chmod +x gradlew
  
addons:
  sonarcloud:
    organization: "fmohr-github"
   
   
script:
  - ./gradlew build -x test 
  - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
  - unzip sonar-scanner-cli-3.2.0.1227-linux.zip
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/sonar-scanner-cli-3.2.0.1227-linux/bin
  - sonar-scanner
 

branches:
  only:
  - master
  - development