language: java
install: true
sudo: false  # faster builds

# Cache gradle files:
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - openjdk8


before_script: 
  - chmod +x gradlew
  - javac core/domains/test/prototypes/test3/strategies/strategy2/FScoreNoFiles.java
  - java FScoreNoFiles
  
addons:
  sonarcloud:
    organization: "fmohr-github"
   
   
script:
  - ./gradlew build
  - ./gradlew generateJavadoc
  - 'if [ "$TRAVIS_PULL_REQUEST_SLUG" = "$TRAVIS_REPO_SLUG" ]; then sonar-scanner; fi' # sonar only on internal PR

branches:
  only:
  - master
  - development